version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "widen"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
